# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

version: '2.3'
services:
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
  flower:
    extends:
      file: docker-services.yml
      service: flower
  kibana:
    extends:
      file: docker-services.yml
      service: kibana
  ui:
    build:
      context: ui/docker
      dockerfile: Dockerfile-ui
    ports:
     - "8081:8081"
    volumes:
      - .:/opt/inspire/ui

  web:
    extends:
      file: docker-services.yml
      service: app
    ports:
     - "8000:8000"
    command: pipenv run gunicorn --reload -b 0.0.0.0:8000  --access-logfile "-" --error-logfile - inspirehep.wsgi:application
    volumes:
      - .:/opt/inspire

  worker:
    extends:
      file: docker-services.yml
      service: app
    command: ./scripts/server
    volumes:
      - .:/opt/inspire
    depends_on:
      - db
      - es
      - mq
      - cache
